// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eidmiavhqojhpvftluwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZG1pYXZocW9qaHB2ZnRsdXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTg4MjEsImV4cCI6MjA3MDM5NDgyMX0.Qt7TNGCVcmz_yUqzdaSiy2mxzhcT7xWFu-Q0Cj82muo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});